[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[project]
name = "datachat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AlbertM", email = "rinkorn@mail.ru" }
]
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.2.0",
    "langchain>=1.2.0",
    "langchain-openai>=1.1.6",
    "loguru>=0.7.3",
    "matplotlib>=3.7.5",
    "pandasai>=2.3.2",
    "pandasai-litellm>=0.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "pre-commit>=4.5.0",
]
lint = [
    "mypy>=1.19.0",
    "ruff>=0.14.8",
]
test = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

[tool.uv]
link-mode = "copy"

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-line-length = 120
